apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: railslation
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "destiny161618@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx